name: on pull request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**/*"

jobs:
  build:
    uses: ./.github/workflows/build-pkg.yml

  website:
    needs: build
    uses: ./.github/workflows/build-website.yml
    with:
      environment: development
