name: on pull request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**/*"

jobs:
  build-wasm:
    uses: ./.github/workflows/build-wasm.yml

  build-pkg:
    needs: build-wasm
    uses: ./.github/workflows/build-pkg.yml

  build-website:
    needs: build-pkg
    uses: ./.github/workflows/build-website.yml
    with:
      environment: development
